### bashrc ---                                      -*- mode: shell-script;  -*-

## Copyright (C) 2021  lebidouilleur

## Author: lebidouilleur <lebidouilleur@icloud.com>
## Keywords:

## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.

## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

### Commentary:

#

### Code:



# Path to BASH dotfiles directory.
export SH_DIR="{{BASH}}"


# Set the name of the theme you want to use.
# NOTE: - Officially supported themes can be found in `themes/' directory.
#       - User custom themes should be added in `custom/themes/' directory.
# If SH_THEME is set to `default' then no theme will be used and raw bash shell
# will be displaying.  If `SH_THEME' is set to `random' then a random theme will
# be loaded at each startup.
export SH_THEME="default"


# Set the plugins you want to use.
# NOTE: - Officially supported plugins can be found in `plugins/' directory.
#       - User custom plugins should be added in `custom/plugins/' directory.
# Default: SH_PLUGINS=(base64 extract man)
export SH_PLUGINS=(base64 extract man)


# Set the current version of these dotfiles.
export SH_VERSION=1.0-dev


# Set the minimum version of GNU/Bash required to run these dotfiles.
export BASH_MINIMUM_VERSION=5.0.0


# Enable daily checks for update.  Set to `false` to disable.
export ENABLE_AUTO_UPDATE="true"


# Enable auto-update without prompting.  Set to `false` to disable.
export ENABLE_UPDATE_WITHOUT_PROMPT="true"


# Enable colors in `ls' output.  Set to `false` to disable.
export ENABLE_LS_COLORS="true"


# Enable colors in `grep' output. Set to `false` to disable.
export ENABLE_GREP_COLORS="true"


# Set the following variable to `true' if you want to enable marking untracked
# files under VCS as dirty.  This makes status check faster for large
# repositories.
export ENABLE_UNTRACKED_FILES_AS_DIRTY="false"


# Set the following variable to `true' if you want to enable logging and debugging.
export ENABLE_DEBUGGING="false"


# In case language environement need to be manually set.
export LANG=en_US.UTF-8


# A minimal and standard PATH.
export PATH="/usr/sbin:/usr/bin:/sbin:/bin"


# Path to man pages.
export MANPATH="/usr/local/man:/usr/share/man"


# Prefered editor for local and remote sessions.
if [ -n $SSH_CONNECTION ]; then
    export EDITOR='vi'
else
    export EDITOR='vi'
fi


# Default compilation flags.
export CHOST="{{UNAMEM}}-{{UNAMES}}"
export CFLAGS="-march=native -mtune=native -Os -pipe -pedantic"
export CXXFLAGS="${CFLAGS}"
export MAKEOPTS="-j4"


# Bootstrap BASH dotfiles setup!
source $SH_DIR/bootstrap.sh
