#!/usr/bin/env dash

## Copyright (C) 2022  lebidouilleur

## Author: lebidouilleur <lebidouilleur@icloud.com>
## Keywords:

### Commentary:

##

### Includes:
. library.sh

### Code:



# No magic strings for reusability
CONTEXT_INSTALL_DIR="${HOME}/.local/bin/context"
CONTEXT_TEXMF_DIR="${CONTEXT_INSTALL_DIR}/tex/texmf"
CONTEXT_FONTS_DIR="$CONTEXT_INSTALL_DIR/tex/texmf-fonts"


print_usage() {
    printf "Usage: ctex <commands> [optionals]...\n"
    printf "    ${TEXT_BOLD}commands${TEXT_RESET}:\n"
    printf "        ${TEXT_FOREGROUND_RED}install${TEXT_RESET}            install context executables and environment\n"
    printf "        ${TEXT_FOREGROUND_RED}uninstall${TEXT_RESET}          uninstall context and associated files\n"
    printf "        ${TEXT_FOREGROUND_RED}update${TEXT_RESET}             update context executables and environment\n"
    printf "\n"
    printf "        ${TEXT_FOREGROUND_RED}font${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}[font]${TEXT_RESET}        install the given font from CTAN\n"
    printf "        ${TEXT_FOREGROUND_RED}font${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}all${TEXT_RESET}           install all fonts from CTAN\n"
    printf "        ${TEXT_FOREGROUND_RED}font${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}google${TEXT_RESET}        install all fonts from Google Fonts\n"
    printf "\n"
    printf "        ${TEXT_FOREGROUND_RED}module${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}[module]${TEXT_RESET}    install the given module from CTAN\n"
    printf "        ${TEXT_FOREGROUND_RED}module${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}all${TEXT_RESET}         install all modules from CTAN\n"
}


print_log() {
    if [ ${#} -eq 0 ]; then
        echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: error: wrong number of arguments" >&2
    elif [ ${#} -eq 1 ]; then
        echo "[$(date +'%Y-%m-%d %H:%M:%S')]: ${1}"
    else
        header="${1}"
        shift
        case "${header}" in
            error|err) printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: ${red}error${RESET}: ${@}\n" >&2 ;;
            warning|warn) printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: ${yellow}warning${RESET}: ${@}\n" >&2 ;;
        esac
    fi
}


print_error() {
    print_log "error" "${*}"
}


print_warning() {
    print_log "warning" "${*}"
}


# There is an issue if the user does not provide any argument
if [ ${#} -eq 0 ]
then
    print_usage
    exit 1
fi




# ===============================================================================




install_context() {
    print_log "Installing ConTEXt in $CONTEXT_INSTALL_DIR..."

    if [ ! -d "$CONTEXT_INSTALL_DIR" ]
    then
        mkdir -p "$CONTEXT_INSTALL_DIR"
    else
        print_error "ConTEXt is already installed."
        print_error "Please use 'ctex update' to update your ConTEXt installation."
        exit 1
    fi

    cd "$CONTEXT_INSTALL_DIR"

    print_log "Downloading ConTEXt installer..."
    curl --silent http://lmtx.pragma-ade.nl/install-lmtx/context-osx-64.zip -o context-osx-64.zip

    print_log "Extracting ConTEXt installer..."
    unzip -qq context-osx-64.zip

    print_log "Running ConTEXt installer..."
    sh ./install.sh

    if [ $? -eq 0 ]
    then
        print_log "ConTEXt is fully installed!"
    else
        print_log "ConTEXt installation failed..."
        rm -rf "$CONTEXT_INSTALL_DIR"
        exit 1
    fi
}




update_context() {
    print_log "Updating ConTEXt in $CONTEXT_INSTALL_DIR..."

    if [ ! -d "$CONTEXT_INSTALL_DIR" ]
    then
        print_log "No ConTEXt installation found..."
        print_log "Please install ConTEXt first."
        exit 1
    fi

    cd $CONTEXT_INSTALL_DIR
    sh ./install.sh

    if [ $? -eq 0 ]
    then
        print_log "ConTEXt has been updated!"
    else
        print_log "An error has occurred..."
        print_log "Retry the update..."
        exit 1
    fi
}




install_ctan_fonts() {
    print_log "Downloading CTAN fonts in $CONTEXT_FONTS_DIR..."

    if [ ! -d "$CONTEXT_FONTS_DIR" ]
    then
        print_log "Your ConTEXt installation has some issues..."
        print_log "Please fix these issues before installing fonts."
    fi

    cd "$CONTEXT_FONTS_DIR"

    case "$1" in
        all) dl http://mirrors.ctan.org/fonts zip ;;
        *)   aria2c "http://mirrors.ctan.org/fonts/${1}.zip" ;;
    esac

    print_log "Extract fonts..."
    for font in *.zip
    do
        extract "$font"
    done

    read -p "Delete font archives? [y/N] " -r answer
    if [ "$answer" != "${answer#[Yy]}" ]
    then
        rm -rf *.zip
    fi

    print_log "Updating ConTEXt environment..."
    mtxrun --generate
    mtxrun --script font --reload
}




install_google_fonts() {
    USER_FONTS_DIR="${HOME}/Library/Fonts"
    GOOGLE_FONTS="Google Fonts"
    GOOGLE_FONTS_DIR="${USER_FONTS_DIR}/${GOOGLE_FONTS}"

    if [ ! -d "${GOOGLE_FONTS_DIR}" ]
    then
        print_log "Installing Google Fonts..."
        git clone --depth 1 https://github.com/google/fonts.git "${GOOGLE_FONTS_DIR}"

        if [ $? -eq 0 ]
        then
            print_log "Google Fonts successfully installed!"
            return 0
        else
            print_log "Error while installing Google Fonts..."
            rm -rf "${GOOGLE_FONTS_DIR}"
            exit 1
        fi
    else
        print_log "Updating Google Fonts..."
        cd "${GOOGLE_FONTS_DIR}"
        git pull origin main

        if [ $? -eq 0 ]
        then
            print_log "Google Fonts successfully updated!"
            return 0
        else
            print_log "Error while updating Google Fonts..."
            exit 1
        fi
    fi
}




install_third_modules() {
    print_log "Downloading CTAN fonts in $CONTEXT_MODULES_DIR..."

    if [ ! -d "$CONTEXT_MODULES_DIR" ]
    then
        print_log "Your ConTEXt installation has some issues..."
        print_log "Please fix these issues before installing third party modules."
    fi

    cd "$CONTEXT_MODULES_DIR"

    case "$1" in
        all) dl http://mirrors.ctan.org/macros/context/contrib zip ;;
        *)   aria2c "http://mirrors.ctan.org/macros/context/contrib/${1}.zip" ;;
    esac

    print_log "Extract modules..."
    for module in *.zip
    do
        unzip -qq "$module"
    done

    print_log "Installing modules..."
    context --generate >/dev/null 2>&1

    if [ $? -eq 0 ]
    then
        print_log "Modules successfully installed!"
    else
        print_log "Error while installing modules..."
    fi

    read -p "Delete module archives? [y/N] " -r answer
    if [ "$answer" != "${answer#[Yy]}" ]
    then
        rm -rf *.zip
    fi
}



if [ ${#} -ge 1 ]
then
    CURRENT_DIR=$(pwd)

    case $1 in
        install)   install_context ;;
        uninstall) rm -rf "${CONTEXT_INSTALL_DIR}" ;;
        update)    update_context ;;
        font)      [ "$2" = "google" ] && install_google_fonts || install_ctan_fonts "$2" ;;
        module)    install_third_modules "$2" ;;
    esac


    cd $CURRENT_DIR
fi
