#!/usr/bin/env dash

## Copyright (C) 2022  lebidouilleur

## Author: lebidouilleur <lebidouilleur@icloud.com>
## Keywords:

### Commentary:

##

### Includes:
. library.sh

### Code:


# No magic strings for reusability
CONTEXT_INSTALL_DIR="${HOME}/.local/bin/context"
CONTEXT_TEXMF_DIR="${CONTEXT_INSTALL_DIR}/tex/texmf"
CONTEXT_FONTS_DIR="$CONTEXT_INSTALL_DIR/tex/texmf-fonts"
CONTEXT_MODULES_DIR="$CONTEXT_INSTALL_DIR/tex/texmf-modules"


print_usage() {
    printf "Usage: ${TEXT_BOLD}ctex${TEXT_RESET} ${TEXT_UNDERLINE}<commands>${TEXT_RESET} [optionals]...\n"
    printf "    commands:\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}install${TEXT_RESET}            install context executables and environment\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}uninstall${TEXT_RESET}          uninstall context and associated files\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}upgrade${TEXT_RESET}            update context executables and environment\n"
    printf "\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}font${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}[font]${TEXT_RESET}        install the given font from CTAN\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}font${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}all${TEXT_RESET}           install all fonts from CTAN\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}font${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}google${TEXT_RESET}        install all fonts from Google Fonts\n"
    printf "\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}module${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}[module]${TEXT_RESET}    install the given module from CTAN\n"
    printf "        ${TEXT_FOREGROUND_MAGENTA}module${TEXT_RESET} ${TEXT_FOREGROUND_CYAN}all${TEXT_RESET}         install all modules from CTAN\n"
}


# There is an issue if the user does not provide any argument
if [ ${#} -eq 0 ]; then
    print_usage
    exit 1
fi




# ===============================================================================




install_context() {
    printf "Installing ConTeXt in $CONTEXT_INSTALL_DIR...\n"

    if [ ! -d "$CONTEXT_INSTALL_DIR" ]; then
        mkdir -p "$CONTEXT_INSTALL_DIR"
    else
        print_error "ConTeXt is already installed.\n"
        print_error "Please use 'ctex update' to update your ConTeXt installation.\n"
        exit 1
    fi

    cd "$CONTEXT_INSTALL_DIR"

    printf "Downloading ConTeXt installer...\n"
    curl --silent http://lmtx.pragma-ade.nl/install-lmtx/context-osx-64.zip -o context-osx-64.zip

    printf "Extracting ConTeXt installer...\n"
    unzip -qq context-osx-64.zip

    printf "Running ConTeXt installer...\n"
    sh ./install.sh >/dev/null >&1

    if [ $? -eq 0 ]; then
        printf "ConTeXt is fully installed!\n"
    else
        print_error "ConTeXt installation failed...\n"
        rm -rf "$CONTEXT_INSTALL_DIR"
        exit 1
    fi
}




upgrade_context() {
    printf "Updating ConTeXt in $CONTEXT_INSTALL_DIR...\n"

    if [ ! -d "$CONTEXT_INSTALL_DIR" ]; then
        print_error "No ConTeXt installation found...\n"
        print_error "Please install ConTeXt first.\n"
        exit 1
    fi

    cd $CONTEXT_INSTALL_DIR
    sh ./install.sh >/dev/null >&1

    if [ $? -eq 0 ]; then
        printf "Updating ConTeXt environment...\n"
        # Fonts
        mtxrun --generate >/dev/null >&1
        mtxrun --script font --reload >/dev/null >&1

        # Modules
        context --generate >/dev/null >&1

        printf "ConTeXt has been upgraded!\n"
    else
        print_error "An error has occurred...\n"
        print_error "Retry the upgrade...\n"
        exit 1
    fi
}




install_ctan_fonts() {
    printf "Downloading CTAN fonts in $CONTEXT_FONTS_DIR...\n"

    if [ ! -d "$CONTEXT_FONTS_DIR" ]; then
        printf "Your ConTeXt installation has some issues...\n"
        printf "Please fix these issues before installing fonts.\n"
    fi

    cd "$CONTEXT_FONTS_DIR"

    case "$1" in
        all) dl http://mirrors.ctan.org/fonts zip ;;
        *)   aria2c "http://mirrors.ctan.org/fonts/${1}.zip" ;;
    esac

    printf "Extract fonts...\n"
    for font in *.zip; do
        extract "$font"
    done

    read -p "Delete font archives? [y/N] " -r answer
    if [ "$answer" != "${answer#[Yy]}" ]; then
        rm -rf *.zip
    fi

    printf "Updating ConTeXt environment...\n"
    mtxrun --generate
    mtxrun --script font --reload
}




install_google_fonts() {
    USER_FONTS_DIR="${HOME}/Library/Fonts"
    GOOGLE_FONTS="Google Fonts"
    GOOGLE_FONTS_DIR="${USER_FONTS_DIR}/${GOOGLE_FONTS}"

    if [ ! -d "${GOOGLE_FONTS_DIR}" ]; then
        printf "Installing Google Fonts...\n"
        git clone --depth 1 https://github.com/google/fonts.git "${GOOGLE_FONTS_DIR}"

        if [ $? -eq 0 ]; then
            printf "Google Fonts successfully installed!\n"
            return 0
        else
            printf "Error while installing Google Fonts...\n"
            rm -rf "${GOOGLE_FONTS_DIR}"
            exit 1
        fi
    else
        printf "Updating Google Fonts..."
        cd "${GOOGLE_FONTS_DIR}"
        git pull origin main

        if [ $? -eq 0 ]; then
            printf "Google Fonts successfully updated!\n"
            return 0
        else
            printf "Error while updating Google Fonts...\n"
            exit 1
        fi
    fi
}




install_third_modules() {
    cd $CONTEXT_INSTALL_DIR

    rsync -rltv --del rsync://contextgarden.net/minimals/current/modules/ modules
    rsync -rlt --exclude=/VERSION --del modules/*/ tex/texmf-modules
    #rm -rf modules
    mtxrun --generate
    mtxrun --script font --reload
}



if [ ${#} -ge 1 ]; then
    CURRENT_DIR=$(pwd)

    case $1 in
        install)   install_context ;;
        uninstall) rm -rf "${CONTEXT_INSTALL_DIR}" ;;
        upgrade)   upgrade_context ;;
        font)      [ "$2" = "google" ] && install_google_fonts || install_ctan_fonts "$2" ;;
        module)    install_third_modules ;;
        help)      print_usage ;;
    esac


    cd $CURRENT_DIR
fi
