#!/usr/bin/env dash

## Copyright (C) 2021  lebidouilleur

## Author: lebidouilleur <lebidouilleur@icloud.com>
## Keywords:

### Commentary:

##

### Code:



print_usage() {
    echo "Usage: extract [option] <archives> ..."
    echo "    options:"
    echo "        -h  show this message and exit"
    echo "        -v  verbosely list files processed"
}


# Define global variable for un/quiet extraction
verbose='v'
zipverbose='-qq' # quiet zip
rarverbose='q' # quiet rar


# There is an issue if the user does not provide any argument
if [ ${#} -eq 0 ]
then
    print_usage
    exit 1
fi


# Check for arguments
while getopts ":hv" options
do
    case $options in
        v)   verbose='v'; zipverbose='' ; rarverbose='' ;;
        h|?) print_usage ; exit 1 ;;
    esac
done ; shift $((OPTIND-1))


# Finaly extracting archives
while [ ${#} -gt 0 ]
do
    if [ -f "$1" ]
    then
        case "$1" in
            *.tar)                  tar x${verbose}f         "$1" ;;
            *.tar.bz2|*.tbz|*.tbz2) tar x${verbose}jf        "$1" ;;
            *.tar.gz|*.tgz)         tar x${verbose}zf        "$1" ;;
            *.tar.xz|*.txz)         tar --xz -x${verbose}f   "$1" ;;
            *.tar.zma|*.tlz)        tar --lzma -x${verbose}f "$1" ;;
            *.bz2)                  bunzip2                  "$1" ;;
            *.gz)                   gunzip                   "$1" ;;
            *.xz)                   unxz                     "$1" ;;
            *.lzma)                 unlzma                   "$1" ;;
            *.7z)                   7za x                    "$1" ;;
            *.Z)                    uncompress               "$1" ;;
            *.zip)                  unzip ${zipverbose} "$1" -d .tmp &&
                                       mkdir "${1%.*}"     &&
                                       mv .tmp/* "${1%.*}" &&
                                       rm -rf .tmp
                                    ;;
            *.xpi|*.ipsw)           unzip ${zipverbose} "$1" -d .tmp &&
                                       mkdir "${1%.*}"     &&
                                       mv .tmp/* "${1%.*}" &&
                                       rm -rf .tmp
                                    ;;
            *.jar|*.apk)            unzip ${zipverbose} "$1" -d .tmp &&
                                       mkdir "${1%.*}"     &&
                                       mv .tmp/* "${1%.*}" &&
                                       rm -rf .tmp
                                    ;;
            *.cbz)                  unzip ${zipverbose} "$1" -d .tmp &&
                                       mkdir "${1%.*}"     &&
                                       mv .tmp/* "${1%.*}" &&
                                       rm -rf .tmp
                                    ;;
            *.cbr)                  unrar x -id${rarverbose} -ad "$1" ;;
            *.rar)                  unrar x -id${rarverbose} -ad "$1" ;;
            *.deb)                  dpkg-deb -x${verbose} "$1" "${1%.*}" ;;
            *.rpm)                  rpm2cpio "$1" | cpio -idm${verbose} ;;
            *.pkg)                  pkgutil --expand "$1" "${1%.*}" ;;

            *) echo "extract: $1: cannot be extracted via extract" ;;
        esac
    else
        echo "extract: $1: no such file"
    fi
    shift
done
